import {
    profile,
    user1,
    user2,
    user3,
    user4,
    user5,
    user6,
    user7,
    user8,
    user9,
  } from "../../assets/images";
  
export const date = [
    {
      id: 1,
      imgUrl: user1,
      name: "Dianna",
      lastName: "Jones",
      age: 25,
      city: "New York",
      country: "USA",
    },
    {
      id: 2,
      imgUrl: user2,
      name: "Jane",
      lastName: "Smith",
      age: 28,
      city: "Los Angeles",
      country: "USA",
    },
    {
      id: 3,
      imgUrl: user3,
      name: "Chiara",
      lastName: "Doe",
      age: 26,
      city: "London",
      country: "UK",
    },
    {
      id: 4,
      imgUrl: user4,
      name: "Ella",
      lastName: "Williams",
      age: 29,
      city: "Sydney",
      country: "Australia",
    },
    {
      id: 5,
      imgUrl: user5,
      name: "Jullie",
      lastName: "Brown",
      age: 30,
      city: "Paris",
      country: "France",
    },
    {
      id: 6,
      imgUrl: user6,
      name: "Olivia",
      lastName: "Miller",
      age: 27,
      city: "Berlin",
      country: "Germany",
    },
    {
      id: 7,
      imgUrl: user7,
      name: "William",
      lastName: "Wilson",
      age: 31,
      city: "Toronto",
      country: "Canada",
    },
    {
      id: 8,
      imgUrl: user8,
      name: "Sophia",
      lastName: "Moore",
      age: 29,
      city: "Tokyo",
      country: "Japan",
    },
    {
      id: 9,
      imgUrl: user9,
      name: "Diana",
      lastName: "Taylor",
      age: 32,
      city: "Mumbai",
      country: "India",
    },
    {
      id: 10,
      imgUrl: user4,
      name: "Alex",
      lastName: "Anderson",
      age: 30,
      city: "Moscow",
      country: "Russia",
    },
  ];
  